import type { Locale } from "../lib/i18n.js";

export const geekIdlePhrases: Record<Locale, readonly string[]> = {
  en: [
    "The API returned 200 and I still don't trust it.",
    "I named the server Gandalf. It blocks every request.",
    "My regex works, but no one knows why.",
    "The bug disappeared when I opened DevTools.",
    "I added one log and fixed production.",
    "The database is judging my query plan.",
    "The cloud is just someone else's haunted computer.",
    "My container needs emotional orchestration.",
    "The type checker found my personality flaw.",
    "I pushed a hotfix and felt the room get colder.",
    "The queue says eventual. It never said when.",
    "My branch has lore now.",
    "This function has more callbacks than friends.",
    "The cron job only fails when I sleep.",
    "I optimized it from slow to mysteriously fast.",
    "The feature flag is now a load-bearing wall.",
    "My dependency tree is becoming a forest.",
    "The WebSocket left me on read.",
    "I asked the AI; now we are both confused.",
    'The bug report says "sometimes," my favorite unit test.'
  ],
  ko: [
    "API가 200을 반환했는데도 믿음이 안 가.",
    "서버 이름을 간달프로 지었더니 모든 요청을 막네.",
    "정규식은 작동하는데 아무도 이유를 몰라.",
    "개발자 도구를 여니까 버그가 사라졌어.",
    "로그 하나 추가했더니 프로덕션이 고쳐졌어.",
    "데이터베이스가 내 쿼리 계획을 심사하고 있어.",
    "클라우드는 남의 유령 들린 컴퓨터일 뿐이야.",
    "내 컨테이너에는 정서적 오케스트레이션이 필요해.",
    "타입 검사기가 내 성격 결함을 찾아냈어.",
    "핫픽스를 푸시했더니 방 안이 서늘해졌어.",
    "큐는 언젠가 된다고만 했지, 언제라고는 안 했어.",
    "내 브랜치에 이제 세계관이 생겼어.",
    "이 함수는 친구보다 콜백이 많아.",
    "크론 작업은 내가 잘 때만 실패해.",
    "느린 코드를 이유 없이 빠른 코드로 최적화했어.",
    "기능 플래그가 이제 내력벽이 됐어.",
    "의존성 트리가 숲이 되어 가고 있어.",
    "웹소켓이 내 메시지를 읽고 답이 없어.",
    "AI에게 물었더니 이제 둘 다 혼란스러워.",
    '버그 리포트에 "가끔"이라고 적혀 있네. 최고의 단위 테스트야.'
  ],
  ja: [
    "APIが200を返したのに、まだ信用できない。",
    "サーバーをガンダルフと名付けたら、全部のリクエストを止める。",
    "正規表現は動く。でも理由は誰も知らない。",
    "開発者ツールを開いたらバグが消えた。",
    "ログを一つ足したら本番が直った。",
    "データベースが私のクエリプランを審査している。",
    "クラウドは誰かの呪われたコンピューターだ。",
    "私のコンテナには心のオーケストレーションが必要だ。",
    "型チェッカーが私の性格の欠陥を見つけた。",
    "ホットフィックスをプッシュしたら部屋が寒くなった。",
    "キューはいつか処理すると言った。いつとは言っていない。",
    "私のブランチに今や伝承がある。",
    "この関数は友達よりコールバックが多い。",
    "cronジョブは私が寝た時だけ失敗する。",
    "遅いコードを謎に速いコードへ最適化した。",
    "機能フラグが建物を支える壁になった。",
    "依存関係ツリーが森になりつつある。",
    "WebSocketに既読スルーされた。",
    "AIに聞いたら、二人とも混乱した。",
    "バグ報告には『時々』とある。最高の単体テストだ。"
  ]
};
